// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLcTItA0VIVHN_14gCfFuGO6YiUopFtg',
    appId: '1:883822460883:web:b9ab37b5d5aeb7874b7926',
    messagingSenderId: '883822460883',
    projectId: 'bloodhero1-5457e',
    authDomain: 'bloodhero1-5457e.firebaseapp.com',
    storageBucket: 'bloodhero1-5457e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQaRPr0dhkcX0L0QgAMbYEMrZL41UMSw',
    appId: '1:883822460883:android:99661c83054b51304b7926',
    messagingSenderId: '883822460883',
    projectId: 'bloodhero1-5457e',
    storageBucket: 'bloodhero1-5457e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZkGDOCzuA5bv0VKaKpVJp2kMs5YiZA8',
    appId: '1:883822460883:ios:269b48efa8d289544b7926',
    messagingSenderId: '883822460883',
    projectId: 'bloodhero1-5457e',
    storageBucket: 'bloodhero1-5457e.firebasestorage.app',
    iosBundleId: 'com.example.bloodHero1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZkGDOCzuA5bv0VKaKpVJp2kMs5YiZA8',
    appId: '1:883822460883:ios:269b48efa8d289544b7926',
    messagingSenderId: '883822460883',
    projectId: 'bloodhero1-5457e',
    storageBucket: 'bloodhero1-5457e.firebasestorage.app',
    iosBundleId: 'com.example.bloodHero1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLcTItA0VIVHN_14gCfFuGO6YiUopFtg',
    appId: '1:883822460883:web:89dd693cbf7613c54b7926',
    messagingSenderId: '883822460883',
    projectId: 'bloodhero1-5457e',
    authDomain: 'bloodhero1-5457e.firebaseapp.com',
    storageBucket: 'bloodhero1-5457e.firebasestorage.app',
  );
}
